load("@rules_vulkan//glsl:defs.bzl", "glsl_shader")

glsl_shader(
    name = "vertex_shader",
    shader = "shader.vert",
    visibility = ["//visibility:public"],
)

glsl_shader(
    name = "fragment_shader",
    shader = "shader.frag",
    visibility = ["//visibility:public"],
)
