name: Bazel Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_bazel
      run: | 
        wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
        chmod +x bazel-0.29.1-installer-linux-x86_64.sh
        sudo ./bazel-0.29.1-installer-linux-x86_64.sh
    - name: install_qt5
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic
        sudo apt update
        sudo apt install qt512base
    - name: build
      run: |
        . /opt/qt512/bin/qt512-env.sh
        bazel build //...
