name: Bazel Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_bazel
      run: | 
        wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
        chmod +x bazel-0.29.1-installer-linux-x86_64.sh
        sudo ./bazel-0.29.1-installer-linux-x86_64.sh
    - name: install_qt5
      run: sudo apt install -y qt5-default
    - name: build
      run: bazel build //...
