name: Bazel Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_bazel
      run: | 
        wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
        chmod +x bazel-0.29.1-installer-linux-x86_64.sh
        sudo ./bazel-0.29.1-installer-linux-x86_64.sh
    - name: install_qt5
      run: |
        sudo apt update
        sudo apt install -y p7zip-full libvulkan-dev
        wget https://code.qt.io/cgit/qbs/qbs.git/plain/scripts/install-qt.sh
        chmod +x install-qt.sh
        sudo ./install-qt.sh --version 5.13.1 --directory /opt/qt qtbase
        sudo ln -s /opt/qt/5.13.1/gcc_64/include /usr/include/x86_64-linux-gnu/qt5
    - name: build
      run: |
        bazel build --linkopt="-L/opt/qt/5.13.1/gcc_64/lib" //...
      env:
        QT_BASE_DIR: /opt/qt/5.13.1/gcc_64
        QTDIR: /opt/qt/5.13.1/gcc_64
        PATH: /opt/qt/5.13.1/gcc_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        LD_LIBRARY_PATH: /opt/qt/5.13.1/gcc_64/lib
